### ISSUE TITLE
Transport encoding issue on search

### ISSUE THREAD

**Issue by ArthurMoore85** [ArthurMoore85/romulus#13]
When attempting to search, the following issue is raised:

`Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/arthur/Projects/romulus/romulus/romulus.py", line 129, in search_rom
    result = self.search.fill_in_form()
  File "/home/arthur/Projects/romulus/romulus/scraping/scraper.py", line 68, in fill_in_form
    self.browser.form = list(self.browser.forms())[0]
  File "/usr/lib/python2.7/site-packages/mechanize/_mechanize.py", line 525, in forms
    return self._factory.forms()
  File "/usr/lib/python2.7/site-packages/mechanize/_html.py", line 267, in forms
    self._current_forms, self._current_global_form = self._get_forms()
  File "/usr/lib/python2.7/site-packages/mechanize/_html.py", line 282, in _get_forms
    if self.root is None:
  File "/usr/lib/python2.7/site-packages/mechanize/_html.py", line 247, in root
    response, verify=False))
  File "/usr/lib/python2.7/site-packages/mechanize/_html.py", line 149, in content_parser
    namespaceHTMLElements=False)
TypeError: parse() got an unexpected keyword argument 'transport_encoding'`

**Comment by ArthurMoore85** [comment]
This issue was invalid and the result of not installing from the pip requirements file.
